### ISSUE TITLE
When I perform `Toggle Breakpoint` in line that has no breakpoint, Tuna create a new breakpoint.

### ISSUE THREAD

**Issue by es-kumagai** [dealforest/Tuna#14]
When I perform `Toggle Breakpoint` in line that has no breakpoint, Tuna set a _new_ disabled continuous breakpoint with no action in the line.

Is this a behavior that you expect?

**Comment by dealforest** [comment]
oops!
It's my stupid miss.

I expect that the new Breakpoint isn't set.
