### ISSUE TITLE
When no variable is selected on Cmd+Shift+', prompt for text input

### ISSUE THREAD

**Issue by wjlafrance** [dealforest/Tuna#16]
Hi @dealforest, thanks for creating this plugin!

I'm trying to solve a very similar problem, getting rid of `println`s in my codebase by replacing with log-and-continue breakpoints. I [asked about it](http://stackoverflow.com/questions/29751219/easily-creating-a-log-and-continue-breakpoint-in-xcode) on StackOverflow.

Tuna gets me most of the way there with the Cmd+Shift+' action. However, sometimes I'm not interested in a variable's contents but just logging that I reached a point in code.

Does this sound like a useful feature to you?

**Comment by dealforest** [comment]
@wjlafrance

Awesome!

I will support it. I think a good way to support it.

**Comment by dealforest** [comment]
@wjlafrance

Hi!

I was corresponding with it.
It will then be available when you press "ctrl + shift + '". or select menu "Set Breakpoint with Input Message"
and press "tab", "tab".

I will improve this behavior someday.
