### ISSUE TITLE
Default shortcuts conflicts with tab switching ones

### ISSUE THREAD

**Issue by bonkey** [dealforest/Tuna#17]
`Cmd-shift-[` and `cmd-shift-]` are default shortcuts to switch tabs on OS X.
Would be great to at least disable it in Tuna, but the best to easily change it.

**Comment by dealforest** [comment]
Oops...
It's my mistake.
Thank you for letting me know!

I change the shortcut.

**Comment by dealforest** [comment]
I fixed it.
used `ctrl-shift-[` and `ctrl-shift-]`.
