### ISSUE TITLE
I sent PR #20, but it may not be a good way.

### ISSUE THREAD

**Issue by es-kumagai** [dealforest/Tuna#21]
I sent a PR https://github.com/dealforest/Tuna/pull/20.
But I think the PR may not be a good way.

Frameworks that want to import may be different by Project each. It doesn't make sense to import a lot of frameworks that is not used by current Project. Some frameworks that specified by the import list may not be present in the current Project.

I think this feature is used to want to import a framework linked to current project. After so, it may not be appropriate to have the import list in Preferences as a common settings.

**Comment by es-kumagai** [comment]
One of the idea,

move the plist file from `~/Library/Preferences/` to `./.Tuna/`. By doing this, you will be able to set import list to each Project, and you can be managed the import list by git too.

When the plist file does not exist, by adopting the default import list, it will avoid the creation of unnecessary plist file.

**Comment by dealforest** [comment]
I have a idea.

I think auto load file of `(PROJECT_ROOT)/.lldbinit`.
It's lldbinit file format and it has the highest priority.

```
(PROJECT_ROOT)/.lldbinit

p @import UIKit
p @import Foundation

command regex pe 's/^[[:space:]]*$/po [[NSProcessInfo processInfo] environment]/'
...
```

If not found `(PROJECT_ROOT)/.lldbinit`,  auto lmport `UIKit` and `Foundation`.

I think that idea is the general-purpose.
What do you think?
