### ISSUE TITLE
"Set print breakpoint" not working

### ISSUE THREAD

**Issue by sebastianludwig** [dealforest/Tuna#24]
Using Xcode 6.4 nothing happens but I hear a "dung" sound.

**Comment by dealforest** [comment]
Hi, thank you for issue.

If it still can't work when you un-check `Automatically continue after evaluating actions`, I think that there is a high possibility of Xcode bug.

Tuna should be the same as the breakpoint to be set manually.

**Comment by sebastianludwig** [comment]
Maybe my description wasn't very good, sorry. The breakpoint isn't added and I don't see a popover at all.

**Comment by dealforest** [comment]
:smile:

If you modify the code during execution, I think you will encounter the phenomenon.
I probably, the divergence between the code and the runtime would have affected.

**Comment by sebastianludwig** [comment]
This is not happening while running the application. I just open a project in Xcode and select `Set print breakpoint` from the menu. 

Expected result: A breakpoint is added to the currently selected line
Actual result: Nothing happens (except for the sound that normally indicates that an action can't be performed).

**Comment by dealforest** [comment]
I understand the situation.

If you press the `⌘ + \`, it becomes expected result.

`Set print breakpoint` try to run after select the variable in editor.

**Comment by sebastianludwig** [comment]
Never mind, it all work's as expected. I was in a hurry, but I should have read the readme more carefully than opening an issue. Thanks for your support! :+1:

**Comment by dealforest** [comment]
No problem:+1:
