### ISSUE TITLE
Not working for Xcode 7.1

### ISSUE THREAD

**Issue by hardikdevios** [dealforest/Tuna#26]
Xcode 7.1 is now officially released please update the plugin

**Comment by dealforest** [comment]
Hi, I had supported Xcode 7.1(https://github.com/dealforest/Tuna/commit/bfcd6835986ad7d5491dd8a5579f7c6f4a170a4d)

Please re-install the plugin.

If you already choise skip-bundle, you execute command on terminal.

`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1`

regards best

**Comment by hardikdevios** [comment]
@dealforest sorry mate i had updated the Plugin before 4 Hours ago no problem will update now

**Comment by dealforest** [comment]
:+1:
